### ISSUE TITLE
zet feedback

### ISSUE THREAD

**Issue by cyemekaray** [cyemekaray/WarbuildsPublic#5]
Ok so I just finished my first game with Warbuilds (HU vs bot NE) and I must say the app worked very well, I used the first strategy I think it was called Grubby's bread and butter and I didn't experience any issues or performance issues, the game ran smoothly at 80-86 fps and had some little block-frames when units spawned but that's because of reforged's poor optimization and besides the very minor spelling mistakes like writing a word with a capital letter even though it's not necessary (but you did everything by yourself so i don't blame you for that) and the fact that Ctrl + F changes to F7 in game, there was nothing else to bother me. I would love some improvements, for instance adding a scaling method for the window since, hiding it is good for me too but I'd really love to keep it there on my screen but at a smaller size or adding a timer, I didn't really know at what minute I was in when I got to some part of the game/strategy and that's prolly all I was thinking about during my time testing it. I'll make sure to test the other strategies too later but for now i'm a little busy.
Overall great app, no performance issues, but I'd suggest a timer maybe(since the game doesn't have one) and some other features :)

**Comment by liquid-cy** [comment]
Ok so I just finished my first game with Warbuilds (HU vs bot NE) and I must say the app worked very well, I used the first strategy I think it was called Grubby's bread and butter and I didn't experience any issues or performance issues, the game ran smoothly at 80-86 fps and had some little block-frames when units spawned but that's because of reforged's poor optimization and besides the very minor spelling mistakes like writing a word with a capital letter even though it's not necessary (but you did everything by yourself so i don't blame you for that) and the fact that Ctrl + F changes to F7 in game, there was nothing else to bother me. I would love some improvements, for instance adding a scaling method for the window since, hiding it is good for me too but I'd really love to keep it there on my screen but at a smaller size or adding a timer, I didn't really know at what minute I was in when I got to some part of the game/strategy and that's prolly all I was thinking about during my time testing it. I'll make sure to test the other strategies too later but for now i'm a little busy.
Overall great app, no performance issues, but I'd suggest a timer maybe(since the game doesn't have one) and some other features :)

**Comment by cyemekaray** [comment]
"ctrl + f changes to f7 in game" fixed! now they open and close with the same hotkey

I fixed some typos as well on this specific build

i will try to add the scaling to the window soon. coding it up is a bit tricky though

there is already a time in game! press f6 to start it up once you picked your build.
